//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

module ConnectifyDAL.Models {
	export class Message
	{
		public Id: number;
		public Text: string;
		public Timestamp: any;
	}
}
